#!/bin/bash


## Run local test
readonly ROOT_DIR=$(git rev-parse --show-superproject-working-tree --show-toplevel | grep "^/")

echo "--- Checking format ---"
cd "$ROOT_DIR"
dprint check

echo "--- Running buf CI and Push buf.build ---"
cd "$ROOT_DIR/proto-def"
buf format --exit-code --diff
buf lint
buf push genome
buf push coexpression

## Prevent from push to main branch
readonly REJECT_PUSH_BRANCHES=('main')

while read local_ref local_sha1 remote_ref remote_sha1
do
    for branch in ${REJECT_PUSH_BRANCHES[@]}; do
        if [[ "${remote_ref##refs/heads/}" = "${branch}" ]]; then
            echo -e "\033[0;32mDo not push to\033[m\033[1;34m ${branch}\033[m \033[0;32mbranch\033[m"
            exit 1
        fi
    done
done



