[workspace]
members = [
  "common",
  "genome",
]

[workspace.dependencies]
serde = { version = "~1.0", features = ["derive"] }
anyhow = "~1.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }