//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "annotation_models")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Vec<u8>,
    pub version: String,
    pub genome_id: Vec<u8>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gene_models::Entity")]
    GeneModels,
    #[sea_orm(
        belongs_to = "super::genomes::Entity",
        from = "Column::GenomeId",
        to = "super::genomes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Genomes,
}

impl Related<super::gene_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneModels.def()
    }
}

impl Related<super::genomes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genomes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
