//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "domain_annotations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub domain_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub transcript_id: Vec<u8>,
    pub start: i32,
    pub end: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::domains::Entity",
        from = "Column::DomainId",
        to = "super::domains::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Domains,
    #[sea_orm(
        belongs_to = "super::transcripts::Entity",
        from = "Column::TranscriptId",
        to = "super::transcripts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transcripts,
}

impl Related<super::domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Domains.def()
    }
}

impl Related<super::transcripts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transcripts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
