//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "genes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Vec<u8>,
    pub gene_id: String,
    pub gene_model_id: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gene_models::Entity",
        from = "Column::GeneModelId",
        to = "super::gene_models::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GeneModels,
    #[sea_orm(has_many = "super::transcripts::Entity")]
    Transcripts,
}

impl Related<super::gene_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneModels.def()
    }
}

impl Related<super::transcripts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transcripts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
