//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "genome_version")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub taxonomy_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::genome_sequence::Entity")]
    GenomeSequence,
    #[sea_orm(
        belongs_to = "super::organism::Entity",
        from = "Column::TaxonomyId",
        to = "super::organism::Column::TaxonomyId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organism,
}

impl Related<super::genome_sequence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GenomeSequence.def()
    }
}

impl Related<super::organism::Entity> for Entity {
    fn to() -> RelationDef {
        super::annotation_model_version::Relation::Organism.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::annotation_model_version::Relation::GenomeVersion
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
