//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "go_terms_annotation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub go_term_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub transcript_id: Vec<u8>,
    pub evidence_code: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub assisgned_by: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::go_terms::Entity",
        from = "Column::GoTermId",
        to = "super::go_terms::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GoTerms,
    #[sea_orm(
        belongs_to = "super::transcripts::Entity",
        from = "Column::TranscriptId",
        to = "super::transcripts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transcripts,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AssisgnedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::go_terms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoTerms.def()
    }
}

impl Related<super::transcripts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transcripts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
