//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use super::sea_orm_active_enums::Namespace;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "go_terms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub namespace: Namespace,
    #[sea_orm(column_type = "Text")]
    pub definition: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::go_terms_annotation::Entity")]
    GoTermsAnnotation,
}

impl Related<super::go_terms_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoTermsAnnotation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
