//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kog_annotations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub kog_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub transcript_id: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kogs::Entity",
        from = "Column::KogId",
        to = "super::kogs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Kogs,
    #[sea_orm(
        belongs_to = "super::transcripts::Entity",
        from = "Column::TranscriptId",
        to = "super::transcripts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transcripts,
}

impl Related<super::kogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Kogs.def()
    }
}

impl Related<super::transcripts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transcripts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
