//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub mod prelude;

pub mod annotation_models;
pub mod domain_annotations;
pub mod domains;
pub mod gene_models;
pub mod genes;
pub mod genomes;
pub mod gff_records;
pub mod go_terms;
pub mod go_terms_annotation;
pub mod kegg_orthologies;
pub mod kegg_orthologies_annotation;
pub mod kegg_pathways;
pub mod kegg_pathways_annotation;
pub mod kegg_reaction;
pub mod kegg_reaction_annotation;
pub mod kog_annotations;
pub mod kogs;
pub mod organisms;
pub mod sea_orm_active_enums;
pub mod transcript_structure;
pub mod transcripts;
pub mod users;
