//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organisms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub taxonomy_id: u32,
    pub name: String,
    pub codon_code: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gene_models::Entity")]
    GeneModels,
    #[sea_orm(has_many = "super::genomes::Entity")]
    Genomes,
}

impl Related<super::gene_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneModels.def()
    }
}

impl Related<super::genomes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genomes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
