//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::annotation_model_version::Entity as AnnotationModelVersion;
pub use super::genome_sequence::Entity as GenomeSequence;
pub use super::genome_version::Entity as GenomeVersion;
pub use super::organism::Entity as Organism;
