//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "category")]
pub enum Category {
    #[sea_orm(string_value = "A")]
    A,
    #[sea_orm(string_value = "K")]
    K,
    #[sea_orm(string_value = "L")]
    L,
    #[sea_orm(string_value = "B")]
    B,
    #[sea_orm(string_value = "J")]
    J,
    #[sea_orm(string_value = "D")]
    D,
    #[sea_orm(string_value = "Y")]
    Y,
    #[sea_orm(string_value = "V")]
    V,
    #[sea_orm(string_value = "T")]
    T,
    #[sea_orm(string_value = "M")]
    M,
    #[sea_orm(string_value = "N")]
    N,
    #[sea_orm(string_value = "Z")]
    Z,
    #[sea_orm(string_value = "W")]
    W,
    #[sea_orm(string_value = "U")]
    U,
    #[sea_orm(string_value = "O")]
    O,
    #[sea_orm(string_value = "E")]
    E,
    #[sea_orm(string_value = "F")]
    F,
    #[sea_orm(string_value = "H")]
    H,
    #[sea_orm(string_value = "I")]
    I,
    #[sea_orm(string_value = "G")]
    G,
    #[sea_orm(string_value = "P")]
    P,
    #[sea_orm(string_value = "C")]
    C,
    #[sea_orm(string_value = "Q")]
    Q,
    #[sea_orm(string_value = "R")]
    R,
    #[sea_orm(string_value = "S")]
    S,
    #[sea_orm(string_value = "X")]
    X,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "namespace")]
pub enum Namespace {
    #[sea_orm(string_value = "BP")]
    Bp,
    #[sea_orm(string_value = "CC")]
    Cc,
    #[sea_orm(string_value = "MF")]
    Mf,
}
