//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Vec<u8>,
    pub orc_id: String,
    pub email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::go_terms_annotation::Entity")]
    GoTermsAnnotation,
}

impl Related<super::go_terms_annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoTermsAnnotation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
